---
title: "ADO-PEC2"
author: "Pío Sierra"
date: "31/5/2020"
output: pdf_document
params:
  counts_file: ./counts.csv
  targets_file: ./targets.csv
  samples: 10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!(require(plyr))) 
  install.packages("plyr")
if(!(require(ggplot2))) 
  install.packages("ggplot2")
if(!(require(RColorBrewer))) 
  install.packages("RColorBrewer")
```


**a) Identify the groups and match groups to files.**  

```{r}
# Leemos los archivos de datos
targets <- read.csv(params$targets_file)
counts <- read.csv2(params$counts_file, header = TRUE, row.names = 1)

# Comprobamos que no falta ningún dato
sum(is.na(targets))
sum(is.na(counts))

# Observamos la distribución de la media y la desviación estándar de las variables.
plot(apply(counts[-1],2,mean))
plot(apply(counts[-1],2,sd))

# En un archivo se usa "." como separador, y en el otro "-". Los igualamos para poder comparar y asegurarnos de que cruzamos los datos correctamente.
colnames(counts) <-gsub("[.]","-", colnames(counts))

# Comprobamos el número de observaciones que hay de cada grupo.
table(targets$Group)

# Tomamos las muestras de targets.
set.seed(123999)
targets_sample <- ddply(targets,.(Group),function(x) x[sample(nrow(x),params$samples),])
table(targets_sample$Group)

# Y ahora las muestras correspondientes en counts
counts_sample <- counts[,which(colnames(counts) %in% targets_sample$Sample_Name)]
identical(colnames(counts), targets$Sample_Name)
```

**b) Quality control of the raw data.**  

```{r}
# Vemos que la disribución tiene un sesgo muy pronunciado. 
# Mostramos una de las muestras como ejemplo, pero ocurre lo mismo en todas.
qplot(counts_sample[,1], geom="histogram") 
# Log base 2 is typically used as it facilitates the conversion back to the original scale: 
# a difference of 1 on the log base 2 scale corresponds to a fold change of 2 on the original count scale. 
pseudoCount = log2(counts_sample + 1)
qplot(pseudoCount[,1], geom="histogram") 

```

**c) Data Normalization.**   

We use the RMA (Robust Multichip Analysis) to perform background correction, normalization and summarize the data.  
```{r include=FALSE}
eset_rma <- rma(rawData)
```
